FROM node:20-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install --quiet
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY package*.json ./

EXPOSE 8085
CMD ["node", "dist/main.js"]
